### ISSUE TITLE
Create allow-list of add-on submitters

### ISSUE THREAD

**Issue by seanbudd** [nvaccess/addon-datastore#1165]
When submitting an add-on, check if the GitHub user ID is on an allow-list, else include a change to register the author GH ID to the add-on ID in a JSON File.
If the user is not registered, fail the PR early and add a comment notifying the author that the PR will be need to be manually approved.
Once the PR is manually merged, subsequent submissions which match the add-on ID and GitHub user ID should be merged automatically.
Once the PR is manually merged, the transformation to views should be manually or automaticaly run.

**Comment by XLTechie** [comment]
The title of this mentions add-on publishers.

The publisher field is currently free-form, and AFAIK, doesn't require a GitHub 
username. I've been using my name and company name, since that's how I prefer my 
add-ons be listed in the store. Currently I submit from my personal Github 
account, but in theory I could have my business partner use his, if his GH ID is 
part of the organization account that appears in my add-on URLs.

So are you talking about publishers here, in the context of the 
somewhat ambiguous Publisher field, or Submitter GitHub IDs for issue 
submitters, or a combination of the two?

Or have I missed the boat entirely?

Is the objective to make certain that add-on owners are the only authorized 
submitters?

**Comment by seanbudd** [comment]
I was using publisher in a synonymous sense of submitter.

>Is the objective to make certain that add-on owners are the only authorized
submitters?

Essentially yes. It's so that we can prevent submitters from potentially hijacking an add-on ID. 
However, it's more about verifying submitters (or publishers) rather than add-on owners. For example, many add-ons are submitted on behalf of others.

**Comment by CyrilleB79** [comment]
Will the allowed submitters list be on a per add-on basis or for the whole Add-on Store?

IMO it should be on a per add-on basis. Indeed, if I was a malicious competitor of Luke's company, I could be allowed to update my own add-ons but I should be prevented from hijacking Luke's ones.

Also will the submitter (GitHub ID) be shown in the add-on store in some way? It would be a good check for security.

**Comment by XLTechie** [comment]
It had not occurred to me that this might be store-scoped instead of add-on 
scoped.

I definitely think add-on scoping is preferable.

I suggest that the first submitter to submit an add-on, is auto-registered for 
that add-on.

Additional submitters can be manually registered, but that would make most of 
this transparent.

**Comment by nvdaes** [comment]
I think that all registrations should be manual, since someone may 
submit an add-on without consulting the original authors, and these may 
want to submit the add-on later or something.

**Comment by XLTechie** [comment]
@nvdaes said:
> I think that all registrations should be manual, since someone may submit an add-on without consulting the original authors, and these may want to submit the add-on later or something.

But how would NV Access know that, without doing a lot of research before approving each registration? Being realistic, are you expecting @seanbudd to do that before each approval?

For example, if I am the first to submit the [Version Collector](https://github.com/opensourcesys/versionCollector) add-on, how is NV Access to know that I am the person permitted to do that, without checking in all of the language directories and such, to be sure that someone else hasn't already submitted it there? And even if they do that, doing so would just be outsourcing the provenance check.

If they aren't going to do that kind of legwork for each registration, then your condition is not met, and I don't see the value of manual registration.

And, if they are just going to rubber stamp each initial submission that "looks good" on the surface, then making it automatic would be much preferable since it will be automatic anyway, just requiring a human to press the button, so to speak.

**Comment by nvdaes** [comment]
imo, if someone sends an addon for the first time, the PR can be pending until manual registration, and in this way possible trols maybe detected by the community before registration. Automatic registration maybe even worse than not registration at all, since someone malicious, for example outside NVDA community, may send serveral addons created by others and this will be further work for @seanbudd or others. But I suppose that Sean is thinking in a procedure since he created this issue.Enviado desde mi iPhoneEl 5 ago 2023, a las 0:58, Luke Davis ***@***.***> escribió:﻿
@nvdaes said:

I think that all registrations should be manual, since someone may submit an add-on without consulting the original authors, and these may want to submit the add-on later or something.

But how would NV Access know that, without doing a lot of research before approving each registration? Being realistic, are you expecting @seanbudd to do that before each approval?
For example, if I am the first to submit the Version Collector add-on, how is NV Access to know that I am the person permitted to do that, without checking in all of the language directories and such, to be sure that someone else hasn't already submitted it there? And even if they do that, doing so would just be outsourcing the provenance check.
If they aren't going to do that kind of legwork for each registration, then your condition is not met, and I don't see the value of manual registration.
And, if they are just going to rubber stamp each initial submission that "looks good" on the surface, then making it automatic would be much preferable since it will be automatic anyway, just requiring a human to press the button, so to speak.

**Comment by XLTechie** [comment]
Regarding manually vs. automatically adding the first submitter of an add-on ID to its allow list:

We have just gotten away from prolonged manual approval processes by NV Access for people to publish add-on updates. Now we are talking about creating prolonged manual approval processes by NV Access for people to release their first add-on.
IMO we should be cautious about that.

Forgive me, @seanbudd, but I observed how long it took (whenever Reef got around to it, essentially), to approve pre-vetted add-on updates. I hesitate to expect this process to be any faster when it involves non-vetted submitter approval. **That is not a knock against NV Access--I know the size of your staff, and there are only so many hours in the day.**

The add-on directory community is already fragmented (e.g. Spanish directory, language directories). I believe NV Access should consider very carefully, before doing anything that makes the store harder to submit to, or involving more delays, than those other directories.

Authors complaining about the initial implementation of the store back end some months ago, has already leaked into the user communities I monitor--leading some to prefer other directories because they are supposedly easier to work with and access. I think a lot of that will die out now that the store is close to being in production versions, but anything that makes authors find other directories easier should be avoided for now, in my opinion.

Manual approval of initial registrations is one such thing to avoid.

**That said, automatic approval of initial registrations, with manual review after the fact, seems much more palatable.**

**Comment by nvdaes** [comment]
Another possibility maybe to approve automatically add-ons send and published from the same GitHub account, and delay a couple of days to approve add-ons send by a different account. For example, if I send WeatherPlus ion behalf of Adriano Barbieri, this may not be approved manually, but if I send clipContentsDesigner from nvdaes account, and the download URL contains nvdaes,this maybe automatically approved and my name can be added to the list.
About directories, I have never used directories created by people who complained about the process of the store, but I don't think that quality of processes maybe reduced to try to prevent people to download add-ons from these directories.

**Comment by nvdaes** [comment]
And other possibility is to avoid a white list,and just, if someone hijacks an id, this person can be blocked so he or she cannot send add-ons to the store. This has the advantage that, if someone cannot send add-ons during a long time or something unforeseen happenns, addons can be updated.
Maybe the best solution.

**Comment by nvdaes** [comment]
I agree with the last plans of PR 1319. However, imo some guidelines for submitters who will be able to send any add-on should be clarified:

- they should have the right of rejecting a request for an addon submission if they detect a malicious code, comments glorifying violence, and should have the right to see the source code and test the add-on, and send feedback to authors and reject a submission in case of a serious concern. They shouldn"t be compelled to send add-ons just because someone requests it, without question.- if these submitters abuse the process, sending addons hijacking ids or in other ways, they should be removed and even, if theny are responsible for mailing lists, websites related to NVDA etc., they should be removed from these responsibilities, and their infraction should be made public.- if they suffer some kind of denigration by someone jho requests an add-on submission, they should have the right to reject to help this person.

**Comment by codeofdusk** [comment]
The process outlined in https://github.com/nvaccess/addon-datastore/pull/1319#issuecomment-1672355804 feels like a reasonable compromise to me!

**Comment by nvdaes** [comment]
@seanbudd, if yoo want me to create a PR for this, adding a json file with each addon ID associated to the person who sends it for latest let me know. If just a person should be associated to an add-on ID, a list for each ID is not needed. I can try to test with github actions on my fork, removing frequentCommitters.json file, so you can see how to choose people who can send any add-on.

**Comment by seanbudd** [comment]
Hi @nvdaes I have some work in progress for this already

**Comment by nvdaes** [comment]
Great. Thanks.Enviado desde mi iPhoneEl 11 ago 2023, a las 6:55, Sean Budd ***@***.***> escribió:﻿
Hi @nvdaes I have some work in progress for this already

**Comment by jmdaweb** [comment]
Hi,
I expect the process to become a trusted submiter is well documented, transparent, and with clear and quantified metrics and indicators that allow third parties to audit it if desired. Otherwise, we may return to a past when someone requested write permission on addonFiles and it was denied or even unanswered.
Regards.

**Comment by nvdaes** [comment]
for clarity, I manifests that i didn"t grant you access to addonFiles since I felt offended, and today I would mention the code of conduct, but i agree about transparency in the process.Enviado desde mi iPhoneEl 12 ago 2023, a las 9:30, José Manuel Delicado ***@***.***> escribió:﻿
Hi,
I expect the process to become a trusted submiter is well documented, transparent, and with clear and quantified metrics and indicators that allow third parties to audit it if desired. Otherwise, we may return to a past when someone requested write permission on addonFiles and it was denied or even unanswered.
Regards.

**Comment by XLTechie** [comment]
Fully agreed with @jmdaweb, I am looking forward to seeing the documentation on 
this.

**Comment by nvdaes** [comment]
Anyway, there's no documentation about the procedure to become an admin of mailing lists, or to be granted access to servers of other organizations. Sometimes metrics are not enough, or other objective information, since reputation is taken account and this is difficult to determine with numbers, but in fact, personally I won't grant access to a project if I don't consider this person as someone reputated.
I voted for someone to be a moderator ofthe addons mailing list when it was owned by Joseph, without metrics, just since that person for me provided good answers to people.
