### ISSUE TITLE
[Submit add-on]: Say product name and version 2023.3

### ISSUE THREAD

**Issue by Nardol** [nvaccess/addon-datastore#127]
### Download URL

https://github.com/Nardol/SayProductNameAndVersion/releases/download/2023.3/sayProductNameAndVersion-2023.3.nvda-addon

### Source URL

https://github.com/Nardol/SayProductNameAndVersion

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by nvdaes** [comment]
The pull request regarding the action was reverted as explained in an existing PR since actions need a personal access token or a similar procedure to run other workflows. I activated this on my personal account and it worked properly including automerge, but seems that this has been reverted and an alternative procedure is planned, as you can see in open pull requests. i write from mobile but this is public thoough I don"t know the enact numbers. 125,  ithink.

**Comment by Nardol** [comment]
OK, it looks like I cannot create the PR using the link.

I'll wait for a notice specifying submitting via issue works as expected...

**Comment by Nardol** [comment]
OK, so I'm continuing to move without understanding what I do with this store :slightly_smiling_face: I think I am going to wait until tomorrow then close this issue and definitely abandon submitting add-on here as it becomes more and more a wast of time for me...

Thanks a lot for your replies anyway. Glad to know it looks working better for other than me :wink:

**Comment by nvdaes** [comment]
I've setup this in my fork, replacing references to nvaccess with nvdaes, my account, and adding the secret.github.token to the merge pull request action, and the PR has been merged and the views branch has been successfully created.
I think that this is almost done in NV Access repo, though maybe merges have to be done by them manually:

https://github.com/nvdaes/addon-datastore/actions/runs/4374476827

**Comment by seanbudd** [comment]
Hi @Nardol - it appears this build is failing because you have no homepage link in the "URL" field of the manifest.
