### ISSUE TITLE
[Submit add-on]: NVDARecorder 2023.03

### ISSUE THREAD

**Issue by ruifontes** [nvaccess/addon-datastore#187]
### Download URL

https://github.com/ruifontes/NVDARecorder/releases/download/2023.03/NVDARecorder-2023.03.nvda-addon

### Source URL

https://github.com/ruifontes/NVDARecorder

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by nvdaes** [comment]
@ruifontes @seanbudd Looking my website for testing the store, I realise that this add-on hasn't been sent to the views branch. Seeing the workflow, seems that numpadMode has been copied instead of this add-on. Seems that numpadMode has been sent just before this one and I don't know if some kind of conflict has happened.

**Comment by nvdaes** [comment]
@ruifontes, no worries, this is fixed when the next add-on has been
submitted, as expected.
I don't think that a workflow needs to be run periodically to ensure
that the views branch is updated, since updates to this branch would
be performed in every add-on submission, though maybe done.
You can ignore my previous comment @ruifontes.

2023-03-11 9:15 GMT+01:00, Noelia Ruiz Martínez ***@***.***>:
