### ISSUE TITLE
Review sub-discussions should not be started for beta or dev add-ons

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/addon-datastore#2111]
I have noticed that review discussions are being cluttered up with version posts for dev and beta add-on versions.

What is the value of this? Generally, beta and dev add-on versions are ephemeral, and are intended for testing or pre-release experimentation. By the time any user reads those reviews, the beta or dev version being reviewed, will likely be vastly out of date.

Plus, if features are being tested, there may be a dozen released and then superseded dev versions of an add-on released for rapid testing. They won't be available in the store any more, but yet their ghosts will remain in meaningless review discussion stubs.

See, for example, the [reviews for Windows App Essentials](https://github.com/nvaccess/addon-datastore/discussions/1950).

I propose that the workflow should not create discussions or posts, for anything other than production releases.

CC @nvdaes, @josephsl, @seanbudd

**Comment by nvdaes** [comment]
I think this is controversial and I don't have a clear opinion about this. Alpha versions of NVDA don't support stable versions of add-ons, and alpha users can also provided feedback for NVDA, so eventually they may want to review add-ons participating in GitHub Discussions from the store.
Also, some stable versions are released just with localization updates and comments for each version may also be superfluous for some users. We can always left reactions to the whole add-on, not for specific versions. This is always optional.

**Comment by seanbudd** [comment]
>Alpha versions of NVDA don't support stable versions of add-ons

This is only true for API breaking releases. 

I do think these comments are quite noisy currently. I'm not sure the best solution - perhaps we drop the comments system entirely. At least until we get some add-on reviews in the first place.

**Comment by nvdaes** [comment]
I would prefer to stop creating new comments for new versions regardless of the channel, since excluding comments just for dev and beta maybe confusing. In the add-on metadata we can include just the discussion url. I am creating an action to get the ID of the specified repo, and also I have a script to create discussions, not ported to an action for now. The create-discussion action used currently works perfectly, though seems to have unmerged work, and I haven"t seen replies to an opened issue where i participated. Node should be updated to version 20, though the current version works. If needed, we may include possible new maintained actions in the pr to drop comments.

**Comment by seanbudd** [comment]
I think it's worth doing. The amount of versions being submitted has really ramped up or was a lot more than expected originally
