### ISSUE TITLE
[Submit add-on]: easyTableNavigator 2.5

### ISSUE THREAD

**Issue by CoBC** [nvaccess/addon-datastore#2943]
### Download URL

https://github.com/CoBC/easyTableNavigator-1/releases/download/2.5/easyTableNavigator-2.5.nvda-addon

### Source URL

https://github.com/CoBC/easyTableNavigator-1

### Publisher

Corentin Bacqué-Cazenave

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by CyrilleB79** [comment]
@gerald-hartig, @michaelDCurran, @SaschaCowley or @Qchristensen:

Usually @seanbudd validates pending checks for first add-on submission in this repository. It seems that he is not available these times (maybe on holiday?).

NVDA 2024.1 has just been released. So many add-on author are currently submitting a new compatible version of their add-ons. For many of them, this submission is the first one since author check has been set up in August 2023.

Could you please have a look at the current request as well as at the other pending requests and validate them soon if appropriated?

API-breaking release process has been quite unpopular in the past among the community; we may hope that the introduction of the Add-on Store with the possibility to override add-on's compatibility may have mitigated this impression. However, delaying the add-on release process in the current period would harm the image of NVDA and its update process again.
