### ISSUE TITLE
[Submit add-on]: Gestor de pomodoros 1.8

### ISSUE THREAD

**Issue by jpavonabian** [nvaccess/addon-datastore#3228]
### Download URL

https://github.com/jpavonabian/Gestor-de-Pomodoros/releases/download/v1.8/gestorDePomodoros-1.8.nvda-addon

### Source URL

https://github.com/jpavonabian/Gestor-de-Pomodoros

### Publisher

Jesús Pavón abián

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by jmdaweb** [comment]
@seanbudd can you please take a look? The add-on name already has its first letter in lowercase.

**Comment by XLTechie** [comment]
@seanbudd, @nvdaes, any idea what's going on here?
I'm wondering if some characterset issue is causing directory or file names to 
be corrupted?

github-actions[bot] wrote:

> Validation Errors for addons/GestorDePomodoros/1.8.0.json:
>
>  *  Submitted json file must be placed in a folder matching the addonId/name 'gestorDePomodoros'

**Comment by nvdaes** [comment]
@XLTechie wrote:

> @seanbudd, @nvdaes, any idea what's going on here?

I don't know. The only thing I can do considering your suggestion about character sets is to make some tests in my fork of the store. I'll do it now in case.

**Comment by nvdaes** [comment]
I think that something maybe wrong due to changes on GitHub. According to my tests, now the gestorDePomodoros 1.5 add-on, previously accepted and currently available on the store, now would be rejected. I've removed it before testing in my fork to avoid pollution in results.
Also, I've submitted by clipContentsDesigner add-on, just changing the name to gestorDePomodoros in buildVars.py, and it has been rejected, always with the same error.
Seems tha something is making GitHub to capitalize folder names starting with words like Gestor or with some characteristics, maybe the end os. I don't know.

This is one of my tests, submitting the clipContentsDesigner add-on with a modified name.
@seanbudd, I don't know if this should be consulted to GitHub, or if you can prevent this modifying some code in the runcreatejson command or something.
Test:
https://github.com/nvdaes/addon-datastore/actions/runs/8678555150

**Comment by nvdaes** [comment]
@seanbudd @jpavonabian , I have been able to submit gestorDePomodoros 1.8 to my fork of this repo, by removing the first version of the add-on, whose ID is capitalized.
I have thought that some .json file of the gestorDePomodoros folder could have a capitalized ID and that this could cause issues in some part of the system, and in fact removing the first .json created for the first version of the add-on submitted to the store, 1.8 pull request has been created successfully:

https://github.com/nvdaes/addon-datastore/actions/runs/8678721108

Regardless of possible improvements to the runcreatejson command, I suggest to take care when add-ons are submitted, and if possible, I would remove the problematic version, unless @seanbudd thinks that this isnot a good idea.

**Comment by nvdaes** [comment]
To give more context, imo the issue may come from the fact that, using git control version when checking out the repo and creating a branch, the capitalized folder, created for the first time, when the first version of the add-on was submitted,  is found, and the json file can be placed there. Seems that removing the first version, and submitting the folder with the first character in lowercase, the last submitted folder is found. So, imo the problem is not that the first add-on version is placed in the folder. Instead, I think that the issue is indirectly fixed when we submit a folder without being capitalized. But certainly, if someone starts providing an add-on ID capitalized, I think this shouldn't be changed.

**Comment by seanbudd** [comment]
Version 1.8 has already been submitted: https://github.com/nvdaes/addon-datastore/blob/master/addons/gestorDePomodoros/1.8.0.json

https://github.com/nvdaes/addon-datastore/pull/996

I'm not sure why the error message is wrong here, but I think the submission here is not necessary?
You cannot submit the same add-on version twice

**Comment by seanbudd** [comment]
@nvdaes 

I don't think this is an issue of casing, as the add-on ID is cased consistently across submissions.

Please see docs here on changing the casing of an add-on

https://github.com/nvaccess/addon-datastore/blob/master/docs/submitters/migratingFromAddonFiles.md#updating-casing-to-lowercamelcasing

**Comment by nvdaes** [comment]
@seanbudd, I accept your explanations as valid. But I saw that the first submitted version was capitalized, in the json file. Also, this add-on has been submitted always from an issue, which creates a json file and a branch via Github actions, Note that my intention is not to say that you are wrong, is just arguing about my opinion and a wish to know what is happening.

**Comment by seanbudd** [comment]
@nvdaes
Are you sure? It appears in lowerCamelCase here?

https://github.com/nvdaes/addon-datastore/blob/master/addons%2FgestorDePomodoros%2F1.3.0.json

**Comment by nvdaes** [comment]
@seanbudd, the first submitted version that I have in my local copy of the datastore is 1.1.1, which iscapitalized. See 1.1.1.json in case:

"addonId": "GestorDePomodoros",

Also, it's possible that Ihave submitted the add-on several times in my fork for testing, but usually I try to remove the version before submitting another one in my tests.
I have done a reset --hard to reply the copy of NV Access add-on datastore repo, and 1.1.1.json has a capitalized add-on id.
