### ISSUE TITLE
Phonetic Punctuation

### ISSUE THREAD

**Issue by mltony** [nvaccess/addon-datastore#3633]
### Download URL

https://github.com/mltony/nvda-phonetic-punctuation/releases/download/v1.8/phoneticPunctuation-1.8.nvda-addon

### Source URL

https://github.com/mltony/nvda-phonetic-punctuation/

### Publisher

Tony Malykh

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by nvdaes** [comment]
@josephsl  @mltony , I don't see problems looking at the sendJson file in VS Code, but I'll test sending this add-on on my fork.

**Comment by nvdaes** [comment]
@josephsl , you are right. The workflow can be run on my fork after indenting the body of the VirusTotal warning, as mentioned by you. I'll open a PR now.
@mltony , I advice you to keep open this issue. It will need to be relabelled by NV Access so that the workflow creates the PR, merges it to master and so on, when this is fixed.
