### ISSUE TITLE
Perform validation and transformation before creating/merging pull request

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/addon-datastore#455]
While the manual submission is not possible, validation/transformation maybe done before creating and merging pull requests, though branches maybe directly merged from issues. But, for consistency and future improvements, I think it maybe better to create pull requests before merging.
However, if errors are presented when a pull request is created, this may result in open issues and pull request that aren't useful, overloading the system.
Also, if transformation is done from issues, and push fails, for example, due to a version released that doesn't follow a right order, this may be detected as soon as possible.
cc: @seanbudd

**Comment by nvdaes** [comment]
Also, the step to check the number of changed files maybe removed here since it's created just a json metadata file.

**Comment by nvdaes** [comment]
I've tested on my fork, and I don't know how should be reported if a file is not included in the views branch, due to a version not send in order, for example, first was sent 5.0 and later 4.0.
I don't know if this should be done with GitHub Actions, checking diffs in the latest folder, or if this should be managed via the transform repo, raising an error.
Pull request maybe simply avoided, committing and pushing directly. I don't know if this would be desirable. Maybe...

**Comment by seanbudd** [comment]
Hi @nvdaes - I don't think your general proposal is possible. Could you please elaborate on your reasoning for performing these checks together.

>However, if errors are presented when a pull request is created, this may result in open issues and pull request that aren't useful, overloading the system.
A way to avoid this is closing PRs/issues if validation fails. I don't see a need to perform validation and transformation before merging here.

>Also, if transformation is done from issues, and push fails, for example, due to a version released that doesn't follow a right order, this may be detected as soon as possible.

This is not a validation error. Add-on authors are welcome to submit older versions of their add-on. If they submit an old version, it is only logical that only the latest version is available via the latest end point.

>Also, the step to check the number of changed files maybe removed here since it's created just a json metadata file.

Validation checks like this on the PR must remain. For example, it is possible an author submits two different versions of the same add-on.
This would cause an add-on metadata file to modified, rather than a new file being created.

I am going to close this issue as I don't see an existing problem that we can or need to solve here.

**Comment by nvdaes** [comment]
seanbudd commented 

> Could you please elaborate on your reasoning for performing these checks together.

I think you cn ignore my proposal. I was missing the fact that old version can be submitted, and some of us have sent version in descendingorder by mistake. You can see more info on this [thread on the add-ons mailing list](https://nvda-addons.groups.io/g/nvda-addons/topic/98140308).
I'll mention there that this issue has been closed.
