### ISSUE TITLE
[Submit add-on]: unigram 2.0.0

### ISSUE THREAD

**Issue by GerardKessler** [nvaccess/addon-datastore#519]
### Download URL

https://github.com/GerardKessler/Unigram/releases/download/2.0.0/unigram-2.0.0.nvda-addon

### Source URL

https://github.com/GerardKessler/unigram

### Publisher

GerardKessler

### Channel

stable

### License Name

GPL v2

### License URL

https://www.gnu.org/licenses/gpl-2.0.html

**Comment by DraganRatkovich** [comment]
Hello,

@GerardKessler Seeing the Unigram add-on in the add-on data store is really nice, however I think that if the add-on is published publicly in the NVDA add-on data store, comments as well as interface messages must be in English. As far as I know, the addon author always makes addons in Spanish, since the main language for the author is Spanish.

Looking at the source code of the add-on, I can verify that the comments are in Spanish.

@nvdaes Although it is also possible that I am wrong, and if so please correct me as you are one of the developers whose main language is Spanish.

**Comment by nvdaes** [comment]
Hello, this is Noelia, from Spain. I think that add-on comments in source code, as well as documentation and interface messages, unless they are for personal usage, should be in English so that add-ons can be reviewed easily and to make translators work comfortable. I request that this add-on was published on the store, but, though I suggested a piece of code, I wrote it in english, I don"t know if it"s included in this version and I don"t have responsibilities for this add-on. Anyway, there is not any rule that prevents people to write in english, just the purpose of making things easier to the community; cheers.Enviado desde mi iPhoneEl 22 abr 2023, a las 17:27, DraganRatkovich ***@***.***> escribió:﻿
Hello,
@GerardKessler Seeing the Unigram add-on in the add-on data store is really nice, however I think that if the add-on is published publicly in the NVDA add-on data store, comments as well as interface messages must be in English. As far as I know, the addon author always makes addons in Spanish, since the main language for the author is Spanish.
Looking at the source code of the add-on, I can verify that the comments are in Spanish.
@nvdaes Although it is also possible that I am wrong, and if so please correct me as you are one of the developers whose main language is Spanish.

**Comment by GerardKessler** [comment]
Greetings.
Indeed, the chains and the comments are written in my native language, which is Spanish. Unfortunately I don't know enough English to be able to do everything in that language. It is not a lack of will, since if I spoke that language I would have no problem writing it that way. I understand that it is the most convenient as a universal language, however Noelia Ruiz Martínez said through a Telegram group that this issue was not an essential requirement. That's why I decided to push this code to this repository. I am sorry that this double standard exists. And if it is essential that it be this way, all in English, I'm afraid I won't be able to share it with the international community yet until I know enough of the language. Excuse me for bothering you.

**Comment by nvdaes** [comment]
In fact, I explained that writing in English is not a requirement to publish add-ons in this repo, though I recomment to use English for previewers, since writing in other languages may produce a bad impression. I think that one of the best things that can happen when sharing add-ons or whatever is that someone wants to review that work, to learn and improve it. So, even from a selfish point of view, and also to receive more and better feedback, I think that writing in the language and using the conventions of the community where a work is shared is a good idea.Enviado desde mi iPhoneEl 23 abr 2023, a las 1:09, Gera Késsler ***@***.***> escribió:﻿
Greetings.
Indeed, the chains and the comments are written in my native language, which is Spanish. Unfortunately I don't know enough English to be able to do everything in that language. It is not a lack of will, since if I spoke that language I would have no problem writing it that way. I understand that it is the most convenient as a universal language, however Noelia Ruiz Martínez said through a Telegram group that this issue was not an essential requirement. That's why I decided to push this code to this repository. I am sorry that this double standard exists. And if it is essential that it be this way, all in English, I'm afraid I won't be able to share it with the international community yet until I know enough of the language. Excuse me for bothering you.

**Comment by jmdaweb** [comment]
Hi,
I agree in some points. If source code is written in english, reviewing tasks are easier for international community members, regardless of their native language. However, writting in a language you don't know may become a nightmare. I don't see writing in languages other than english as a bad practice nor causes a bad impresion. It's worse for me noticing that the entire add-on has been translated with an automatic translator.
I'm sure Gerardo will try to learn english and code in english in the future, but for now, if the documentation and the interface are translated into english, and the base language is properly set in buildVars.py, what is the problem?
If english becomes mandatory in the future to submit add-ons to the store, despite all my add-ons are in english, I will seriously consider the idea of removing them. "Everything in english" goes against diversity and closes a lot of doors.
It's surprising that this request comes from a person whose mother tongue is not english.
Regards.

**Comment by hxebolax** [comment]
It is unbelievable that in the age of translators there are people almost demanding English because of I don't know what protocols or ethics.

I don't know English and I get around the world with perfection because I rely on the good translators out there.

Does the English speaker know that these translators exist?

Well, the same as I make an effort that they also make a little effort.

An appreciation and a big difference.

The project is NVDA so if I want to contribute to the code I will make an effort to send everything in English since the project is the language that handles.

Being an add-on let's not forget that it is a personal work not linked to the main project.

Therefore I don't think that if you know how to differentiate there are problems to use any language with which the programmer feels more comfortable.

And those who do not know the programmer's language should learn the programmer's language or use like everyone else a fucking translator that surely enriches them a little more than not only with their English.

Remember that making an add-on is something personal and not linked to NVDA, so it is a stupid excuse to say that the English language is the language of the project.

**Comment by seanbudd** [comment]
Hi all,

There is no requirement for add-ons submitted to the add-on store to be in English.

**Comment by seanbudd** [comment]
Hi @GerardKessler - it appears that the download file for unigram 2.0.0 has changed twice since you have submitted it.
In future changing the file downloaded by the release link will make it unavailable to install through the add-on store. For security reasons we need to ensure that the file downloaded by the user is the same file submitted to the add-on store.
Please release a new add-on version and submit it when making changes.
