### ISSUE TITLE
Add-on submission and other doc clarification

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/addon-datastore#95]
### Issue

Since yesterday, this add-on store repo is the repo where add-on submission should be asked, in replacement of old addonFiles repo.
However, there are still unclear points on how to submit a new add-on or an add-on update.

#### Documentation separation
Today, all the documentation is in the main readme. The audience of this readme is for add-on authors, add-on submitters and add-on store developers. It contains:
* A list of requirements for the add-on store
* Design information of the add-on store
* Instructions on how to submit add-ons

I think that this readme should be split in various documents. More specifically from an add-on author point of view, the instructions on how to submit an add-on should not be mixed in the same document with add-on store requirements or design considerations. The repo's main readme could contain just a little intro and 3 linnks to these documents so that each audience only looks at the appropriate information.

The document targetting add-on authors and submitters (in case the submitter is not the author) should contain:
* the instructions on how to submit an add-on
* additional requirements (if any) for an add-on to be submittable to the store if requirements are not the same as the ones required to be installable in NVDA

### Documentation update
The following points should be updated/clarified:

#### Use valid examples
Example is given for the NV Access add-on, 'NVDA - OCR':
If we are talking of NV Access (initial) version of this add-on it is not updated since 2020. And the version present in the migration of the store is the one forked and continued by Łukasz Golonka. So better use an example already present in the store rather than an add-on name that will probably never be in the store (addonId "ocr" instead "nvda-ocr")

#### Version in json

Regarding the json file it is written:
> `<version>` is the add-on version in the form: `Major.Minor.Patch` E.G. "2.4.1"
Is it a requirement? If yes, it is an additional information that needs to be provided since the "version" field in the manifest rather seems to match "addonVersionName" in the json.

#### Versioning scheme
Clarify these points:
* Are there recommendations or additional requirements regarding versioning scheme, especially for dev and beta version.
* The legacy add-ons present in the repo use x.y.1 for dev versions. Is it a requirement, a recommendation or only something that has been done when migrating the add-ons but that does not require to be continued?

#### Auto-check:
> Automated checks for common issues will complete. Either giving feedback or merging the PR.

As I understand this sentence, automated check completion can trigger automatic merge; even if not explicitely written, that's what the sentence seems to mean.
If I am not mistaken, automatic merging is only a project but not yet enabled. Current sitatuation should be documented, even if future project can also remain mentioned.

#### Json fields description
Some fields in the json are the same as the ones in the manifest (even if renamed); other ones are new.
A description of each field should be done, giving the correspondance (if any) in the manifest file in case the field name differ between json and manifest.

**Comment by nvdaes** [comment]
Hi Cyrille, about automated checks, I'm not sure about your comment. You know that checks are done against pull requests sending add-ons, right? You may be asking about a different think. I'm not sure. In case, you can see for example PR #93 . I sent emoticons 16.0 add-on, also available in addonFiles, so that it's not marked as legacy.
And you will see that all checks pass.
If you're asking about a different thing, I'd like to know it.

**Comment by CyrilleB79** [comment]
> Hi Cyrille, about automated checks, I'm not sure about your comment. You know that checks are done against pull requests sending add-ons, right? You may be asking about a different think. I'm not sure. In case, you can see for example PR #93 . I sent emoticons 16.0 add-on, also available in addonFiles, so that it's not marked as legacy. And you will see that all checks pass. If you're asking about a different thing, I'd like to know it.

Thanks Noelia for your feedback.
Sorry, I have not been specific enough. I was thinking to automatic merging rather than auto-check. I have now rephrased this paragraph in the initial description.

**Comment by nvdaes** [comment]
ok. Precisely I"ve tested the automerge feature in cursorlocator repo to figure out how it can work, and it"s the first time that I have enabled it successfully; cheers.Enviado desde mi iPhoneEl 1 mar 2023, a las 15:15, Cyrille Bougot ***@***.***> escribió:﻿

Hi Cyrille, about automated checks, I'm not sure about your comment. You know that checks are done against pull requests sending add-ons, right? You may be asking about a different think. I'm not sure. In case, you can see for example PR #93 . I sent emoticons 16.0 add-on, also available in addonFiles, so that it's not marked as legacy. And you will see that all checks pass. If you're asking about a different thing, I'd like to know it.

Thanks Noelia for your feedback.
Sorry, I have not been specific enough. I was thinking to automatic merging rather than auto-check. I have now rephrased this paragraph in the initial description.

**Comment by CyrilleB79** [comment]
@seanbudd, @michaelDCurran: do NV Access plan to work on this issue soon? Or would you prefer me to submit a proposal through a PR? Thanks.

**Comment by seanbudd** [comment]
@CyrilleB79 , I am currently working on a PR to address this, and document some of the issues Joseph raised as well (e.g. the legacy end point, handling camel case conversion, etc.)

**Comment by seanbudd** [comment]
Thank you for raising this feedback
